# Enable Built-In Features
aha_board: true
question_board: false

# Custom Sidebar Links to External Sites
sidebar:
  
  # Default icon is fa-cloud
  # Must provide a label and url
  - 
    label: "Community"
    url: "https://golearntocode.slack.com/"
    icon: fa-slack
  - 

    label: "NASA"
    url: "www.nasa.gov"

  
