course:
  name: Go Learn To Code
  quarter: Autumn
  year: 2014
  github_url: 
  
sidebar: 
  aha: Aha! Board
  # question: Question Board
  resources: Resources
  about: Syllabus
  slack: [Community, "https://golearntocode.slack.com/"]
  


  
